language: objective-c
osx_image: xcode8.1

install:
  - bundle install
  - pod repo update > /dev/null
  - ./install.sh

script:
  - bundle exec fastlane test

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Antidote'
